### ISSUE TITLE
Add more flexibility to configure credentials

### ISSUE THREAD

**Issue by lucas-dclrcq** [hef/dbman#94]
Hi,

Currently, you can only set a secret name and dbman assumes the keys are `username` and `password`.
To cover all possible usecase it would be great to have more flexibility on how to configure credentials :
- inline username / password in the Database resource to allow using flux substitutes for example
- secret & key in secret for username / password to allow custom key (eg. share the app secret and reuse the app's env vars)

Here is an example of what I have in mind :

```yaml
---
apiVersion: dbman.hef.sh/v1alpha2
kind: Database
metadata:
  name: test
  namespace: default
spec:
  credentials:
    # assumes username / password keys
    secret: test-secret
  database_name: test
  database_server_ref:
    namespace: infrastructure
    name: apps
---
apiVersion: dbman.hef.sh/v1alpha2
kind: Database
metadata:
  name: test
  namespace: default
spec:
  credentials:
    # Inline username & password can be useful if you use flux substitute vars for example
    username: test
    password: "${SOME_FLUX_VAR}"
  database_name: test
  database_server_ref:
    namespace: infrastructure
    name: apps
---
apiVersion: dbman.hef.sh/v1alpha2
kind: Database
metadata:
  name: test
  namespace: default
spec:
  credentials:
    # manually specifying the secret name and key allows reusing an existing app secret
    usernameSecretRef:
      name: test-secret
      key: DB_USERNAME
    passwordSecretRef:
      name: test-secret
      key: DB_PASSWORD
  database_name: test
  database_server_ref:
    namespace: infrastructure
    name: apps
```
